### PR TITLE
Migration to jira.js

### PR DESCRIPTION
**Pull request by MrRefactoring**
Hi @NaridaL! I finally added type support for API responses. I think now you can use my library without pain

### CODE REVIEW

**Comment by NaridaL** [comment]
Hi @MrRefactoring, thanks a lot for going to the trouble of integrating it here! I will check it out on the weekend.

**Comment by NaridaL** [comment]
Unfortunately, I couldn't get this to work against our private JIRA instance. I am also getting XSRF errors.

"XSRF check failed"

There are XSRF cookie settings in the Axios object. Maybe this is related?

**Comment by NaridaL** [comment]
Also see https://github.com/MrRefactoring/jira.js/issues/102

**Comment by MrRefactoring** [comment]
@NaridaL comments resolved. Please check one more time

**Comment by NaridaL** [comment]
Merged with #28

**Pull request closed without merging**
